use conf::Conf;

/// Test that default_value_expr is evaluated in debug assertions
#[derive(Conf)]
#[conf(test)]
#[allow(dead_code)]
pub struct ConfigWithDefaultExpr {
    #[conf(long, default(42))]
    value: i32,

    #[conf(long, default, default_help_str = "0")]
    with_default_trait: i32,

    #[conf(long, default(10 + 5), default_help_str = "15")]
    computed: i32,
}

/// Test that default_value_expr with Option works in debug assertions
#[derive(Conf)]
#[conf(test)]
#[allow(dead_code)]
pub struct ConfigWithDefaultExprOption {
    #[conf(long, default(42), default_help_str = "42")]
    value: Option<i32>,
}

/// Test that complex expressions work in debug assertions
#[derive(Conf)]
#[conf(test)]
#[allow(dead_code)]
pub struct ConfigWithComplexDefaultExpr {
    #[conf(
        long,
        default(vec![1, 2, 3]),
        default_help_str = "vec![1, 2, 3]",
        value_parser = |s: &str| {
            s.split(',')
                .map(|n| n.trim().parse::<i32>())
                .collect::<Result<Vec<_>, _>>()
                .map_err(|e| e.to_string())
        }
    )]
    values: Vec<i32>,
}

// The test functions should be automatically generated by the macro
// and will call debug_asserts() which will evaluate the __default_value__() functions
