use conf::Conf;

#[derive(Conf)]
#[conf(test)]
pub struct SimpleConfig {
    #[arg(short, long)]
    name: String,

    #[arg(short, long)]
    count: i32,

    #[arg(long)]
    verbose: bool,
}

#[derive(Conf)]
#[conf(serde, test)]
pub struct ConfigWithSerde {
    #[arg(long)]
    host: String,

    #[arg(long)]
    port: u16,

    #[arg(long)]
    enabled: bool,
}

#[derive(Conf)]
#[conf(test(should_panic))]
pub struct ConfigWithShouldPanic {
    /// First positional (optional)
    #[conf(pos)]
    optional: Option<String>,

    /// Second positional (required) - INVALID!
    /// This should cause a panic during parser construction
    #[conf(pos)]
    required: String,
}

// The test functions should be automatically generated by the macro
